# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheATeam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheATeam
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SwiftyJSON'
pod 'GooglePlacePicker'
pod 'Alamofire', '~> 4.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  target 'TheATeamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheATeamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
